# Generated by Django 6.0.4 on 2026-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGeneral',
            fields=[
                ('id_areas_generales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'areas_generales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_congreso', models.CharField(max_length=255)),
                ('firma_organizador', models.CharField(blank=True, max_length=255, null=True)),
                ('firma_secretaria', models.CharField(blank=True, max_length=255, null=True)),
                ('firmas_bloqueadas', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'congreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostosCongreso',
            fields=[
                ('id_costos_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_deposito', models.CharField(max_length=255)),
                ('costo_congreso_asistente', models.FloatField()),
                ('costo_congreso_ponente', models.FloatField()),
                ('costo_congreso_comite', models.FloatField()),
            ],
            options={
                'db_table': 'costos_congreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id_dictamen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dictamen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictamenPregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dictamen_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_final', models.DateTimeField()),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('cupos', models.SmallIntegerField(default=0)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FechasCongreso',
            fields=[
                ('id_fechas_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_final_evento', models.DateTimeField()),
                ('fecha_inicio_prepago', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_prepago', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_pago_normal', models.DateTimeField()),
                ('fecha_fin_pago_normal', models.DateTimeField()),
                ('fecha_inicio_inscribir_dictaminador', models.DateTimeField()),
                ('fecha_fin_inscribir_dictaminador', models.DateTimeField()),
                ('fecha_inicio_inscribir_evaluador', models.DateTimeField()),
                ('fecha_fin_inscribir_evaluador', models.DateTimeField()),
                ('fecha_inicio_subida_ponencias', models.DateTimeField()),
                ('fecha_fin_subida_ponencias', models.DateTimeField()),
                ('fecha_inicio_evaluar_resumenes', models.DateTimeField()),
                ('fecha_final_evaluar_resumenes', models.DateTimeField()),
                ('fecha_inicio_evaluar_extensos', models.DateTimeField()),
                ('fecha_fin_evaluar_extensos', models.DateTimeField()),
                ('fecha_inicio_subir_multimedia', models.DateTimeField()),
                ('fecha_fin_subir_multimedia', models.DateTimeField()),
            ],
            options={
                'db_table': 'fechas_congreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('ruta_imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MesasTrabajo',
            fields=[
                ('id_mesas_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mesas_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id_rubrica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rubrica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricaCriterio',
            fields=[
                ('id_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('puntaje_maximo', models.IntegerField()),
            ],
            options={
                'db_table': 'rubrica_criterio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('num_exterior', models.IntegerField()),
                ('num_interior', models.IntegerField(blank=True, null=True)),
                ('modulo_fisico', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id_subareas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('tallerista', models.CharField(max_length=255)),
                ('tipo_participacion', models.CharField(max_length=50)),
                ('id_multimedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id_tipo_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_trabajo',
                'managed': False,
            },
        ),
    ]
