# Generated by Django 6.0.4 on 2026-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresos', '0002_add_firmas_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricaGrupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rubrica_grupo',
                'managed': False,
            },
        ),
    ]
