# Generated by Django 6.0.4 on 2026-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congresos', '0002_rubricagrupo'),
        ('congresos', '0003_rubricagrupo'),
    ]

    operations = [
    ]
