# Generated by Django 6.0.5 on 2026-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresos', '0003_rubricagrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroHasPonencia',
            fields=[
                ('id_libro_has_ponencia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'libro_has_ponencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'libros',
                'managed': False,
            },
        ),
    ]
