# Generated by Django 6.0.4 on 2026-05-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congresos', '0004_librohasponencia_libros'),
        ('congresos', '0004_merge_0002_rubricagrupo_0003_rubricagrupo'),
    ]

    operations = [
    ]
