import { useState, useEffect } from "react";
import { HiCloudUpload, HiDocumentText, HiTrash, HiSparkles, HiMail, HiX, HiCheckCircle } from "react-icons/hi";
import { MdPerson, MdBusiness, MdVerified } from "react-icons/md";
import { BsFillPersonLinesFill, BsFillPersonFill } from "react-icons/bs";
import CertificateTemplate from "./CertificateTemplate";
import { uploadConstanciaApi } from "../../../api/adminApi";

const ROL_COLORS = {
  Dictaminador: { bg: 'bg-purple-100', text: 'text-purple-700', border: 'border-purple-200' },
  Evaluador: { bg: 'bg-blue-100', text: 'text-blue-700', border: 'border-blue-200' },
  Ponente: { bg: 'bg-amber-100', text: 'text-amber-700', border: 'border-amber-200' },
  Asistente: { bg: 'bg-teal-100', text: 'text-teal-700', border: 'border-teal-200' },
  default: { bg: 'bg-gray-100', text: 'text-gray-600', border: 'border-gray-200' },
};

export default function ConstanciaUpload({ selectedUser, signatures = {}, isSignatureLocked = false, idCongreso, congressName, sede, onUploadSuccess }) {
  const [dragActive, setDragActive] = useState(false);
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [successMsg, setSuccessMsg] = useState(false);

  const accessToken = localStorage.getItem('congress_access');
  const rolColors = ROL_COLORS[selectedUser?.rol] || ROL_COLORS.default;

  useEffect(() => {
    setFile(null);
    setIsAutoGenerated(false);
    setSuccessMsg(false);
  }, [selectedUser?.id]);

  useEffect(() => {
    if (file && !isAutoGenerated) {
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [file, isAutoGenerated]);

  const handleGenerateAuto = () => {
    if (!isSignatureLocked) {
      alert("Confirme las firmas institucionales primero.");
      return;
    }
    if (!idCongreso) {
      alert("Seleccione un congreso en el filtro.");
      return;
    }
    setIsProcessing(true);
    setTimeout(() => {
      setFile({ name: `CONSTANCIA_${selectedUser?.nombre?.toUpperCase() || 'PARTICIPANTE'}.pdf` });
      setIsAutoGenerated(true);
      setIsProcessing(false);
      setShowModal(true);
    }, 800);
  };

  const handleFileSelect = (f) => {
    if (!f) return;
    setIsAutoGenerated(false);
    setFile(f);
    setShowModal(true);
  };

  const handleConfirmSend = async () => {
    setIsProcessing(true);
    try {
      let fileToUpload = file;
      if (isAutoGenerated) {
        fileToUpload = new File(
          [JSON.stringify({ user: selectedUser?.id, generated: true })],
          `constancia_${selectedUser?.id}.pdf`,
          { type: "application/pdf" }
        );
      }
      await uploadConstanciaApi(accessToken, selectedUser.id_persona, idCongreso, fileToUpload, selectedUser.rol);
      setIsProcessing(false);
      setShowModal(false);
      setFile(null);
      setIsAutoGenerated(false);
      setSuccessMsg(true);
      setTimeout(() => setSuccessMsg(false), 3000);
      if (onUploadSuccess) onUploadSuccess();
    } catch (error) {
      alert("Error al enviar constancia.");
      setIsProcessing(false);
    }
  };

  const handleDownloadPDF = () => {
    const el = document.getElementById('certificate-to-print');
    if (!el) return;
    const uniqueName = `constancia_${selectedUser?.nombre?.replace(/\s/g, '_') || 'participante'}`;
    const printWindow = window.open('', '', 'width=1200,height=800');
    printWindow.document.write(`
      <html>
        <head>
          <title>${uniqueName}</title>
          <script src="https://cdn.tailwindcss.com"><\/script>
          <style>
            @page { size: landscape; margin: 0; }
            body { margin: 0; -webkit-print-color-adjust: exact; font-family: sans-serif; }
          </style>
        </head>
        <body>${el.innerHTML}
          <script>window.onload=()=>{setTimeout(()=>{window.print();window.close();},1000)};<\/script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  if (!selectedUser) {
    return (
      <div className="bg-white rounded-3xl border border-gray-100 shadow-sm p-8 flex flex-col items-center justify-center gap-4 min-h-[280px] text-gray-300">
        <MdPerson className="text-5xl" />
        <p className="text-sm font-semibold text-center">Selecciona un participante de la lista</p>
      </div>
    );
  }

  return (
    <>
      <div className="flex flex-col gap-0 rounded-3xl overflow-hidden shadow-lg border border-gray-100 animate-in slide-in-from-left duration-400">
        {/* Cabecera con info del participante */}
        <div className="bg-gradient-to-br from-[#005a6a] to-[#007a8a] text-white p-5">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 bg-white/15 rounded-2xl flex items-center justify-center text-2xl shrink-0 border border-white/20">
              {selectedUser.rol === 'Dictaminador' ? <BsFillPersonLinesFill /> : <BsFillPersonFill />}
            </div>
            <div className="flex-1 min-w-0">
              <h3 className="font-black text-base leading-tight truncate">{selectedUser.nombre}</h3>
              <p className="text-white/70 text-xs truncate mt-0.5">{selectedUser.email}</p>
              <div className="flex items-center gap-2 mt-2">
                <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full border ${rolColors.bg} ${rolColors.text} ${rolColors.border}`}>
                  {selectedUser.rol}
                </span>
                {selectedUser.institucion && selectedUser.institucion !== 'N/A' && (
                  <span className="flex items-center gap-1 text-[10px] text-white/60 font-semibold truncate">
                    <MdBusiness className="shrink-0" /> {selectedUser.institucion}
                  </span>
                )}
              </div>
            </div>
          </div>

          {successMsg && (
            <div className="mt-3 flex items-center gap-2 bg-green-500/20 border border-green-400/40 text-green-200 rounded-xl px-3 py-2 text-xs font-bold animate-in fade-in zoom-in duration-300">
              <HiCheckCircle className="text-lg shrink-0" /> Constancia enviada correctamente
            </div>
          )}
        </div>

        {/* Cuerpo */}
        <div className="bg-white p-5 flex flex-col gap-4">
          {/* Botón generar desde plantilla */}
          <button
            onClick={handleGenerateAuto}
            disabled={isProcessing || !isSignatureLocked || !idCongreso}
            className={`w-full py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 transition-all border
              ${(isSignatureLocked && idCongreso)
                ? 'bg-amber-50 text-amber-700 border-amber-200 hover:bg-amber-100 shadow-sm'
                : 'bg-gray-50 text-gray-300 border-gray-100 cursor-not-allowed'}`}
            title={!idCongreso ? "Seleccione un congreso" : !isSignatureLocked ? "Confirme las firmas primero" : ""}
          >
            {isProcessing ? <span className="loading loading-spinner loading-sm"></span> : <HiSparkles />}
            Generar desde Plantilla
          </button>

          <div className="flex items-center gap-3">
            <div className="flex-1 h-px bg-gray-100"></div>
            <span className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">o subir PDF</span>
            <div className="flex-1 h-px bg-gray-100"></div>
          </div>

          {/* Zona drag & drop */}
          <label
            className={`relative flex flex-col items-center justify-center gap-3 p-6 rounded-2xl border-2 border-dashed transition-all cursor-pointer text-center
              ${dragActive ? 'bg-[#005a6a]/5 border-[#005a6a] scale-[1.02]' : 'border-gray-200 hover:border-[#005a6a]/40 hover:bg-gray-50'}`}
            onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
            onDragLeave={() => setDragActive(false)}
            onDrop={(e) => { e.preventDefault(); setDragActive(false); handleFileSelect(e.dataTransfer.files[0]); }}
          >
            <HiCloudUpload className={`text-3xl transition-colors ${dragActive ? 'text-[#005a6a]' : 'text-gray-300'}`} />
            <div>
              <p className="text-sm font-semibold text-gray-600">Arrastra un PDF aquí</p>
              <p className="text-xs text-gray-400">o haz clic para explorar</p>
            </div>
            <input type="file" accept=".pdf" className="hidden" onChange={(e) => handleFileSelect(e.target.files[0])} />
          </label>

          {/* Archivo seleccionado (manual, no auto) */}
          {file && !isAutoGenerated && (
            <div className="flex items-center gap-3 bg-gray-50 rounded-xl p-3 border border-gray-100 animate-in fade-in duration-200">
              <HiDocumentText className="text-2xl text-[#005a6a] shrink-0" />
              <div className="flex-1 min-w-0">
                <p className="text-xs font-bold text-gray-700 truncate">{file.name}</p>
                <p className="text-[10px] text-gray-400">PDF listo para enviar</p>
              </div>
              <button onClick={() => setFile(null)} className="p-1.5 hover:bg-red-50 rounded-lg text-gray-400 hover:text-red-500 transition-colors">
                <HiTrash />
              </button>
              <button
                onClick={() => setShowModal(true)}
                className="px-3 py-1.5 bg-[#005a6a] text-white rounded-lg text-xs font-bold hover:bg-[#004a5a] transition-colors"
              >
                Vista previa
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Modal de previsualización */}
      {showModal && (
        <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4 lg:p-8">
          <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={() => !isProcessing && setShowModal(false)}></div>
          <div className="relative bg-white w-full max-w-6xl rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[95vh]">
            {/* Modal header */}
            <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50 shrink-0">
              <div className="flex items-center gap-3">
                <MdVerified className="text-2xl text-[#005a6a]" />
                <div>
                  <h3 className="font-black text-gray-800 text-sm uppercase tracking-tight">Vista Previa de Constancia</h3>
                  <p className="text-xs text-gray-400">{selectedUser.nombre} — {selectedUser.rol}</p>
                </div>
              </div>
              <button onClick={() => !isProcessing && setShowModal(false)} className="p-2 hover:bg-gray-200 rounded-full transition-colors">
                <HiX className="text-xl text-gray-400" />
              </button>
            </div>

            {/* Vista previa */}
            <div className="flex-1 bg-neutral-200 overflow-auto p-6 flex items-start justify-center">
              <div id="certificate-to-print" className="w-full max-w-5xl shadow-2xl rounded-lg overflow-hidden">
                {isAutoGenerated ? (
                  <CertificateTemplate user={selectedUser} signatures={signatures} congressName={congressName} sede={sede} />
                ) : (
                  <iframe src={previewUrl} className="w-full aspect-[1.414/1] border-none" title="Vista previa" />
                )}
              </div>
            </div>

            {/* Modal footer */}
            <div className="px-6 py-4 bg-white border-t border-gray-100 flex flex-col sm:flex-row gap-3 shrink-0">
              <div className="flex gap-2 flex-1">
                <button
                  disabled={isProcessing}
                  onClick={() => setShowModal(false)}
                  className="px-5 py-2.5 border border-gray-200 rounded-xl font-bold text-gray-500 text-xs hover:bg-gray-50 transition-all uppercase tracking-wide"
                >
                  Cerrar
                </button>
                {isAutoGenerated && (
                  <button
                    onClick={handleDownloadPDF}
                    className="px-5 py-2.5 bg-gray-800 text-white rounded-xl font-bold text-xs flex items-center gap-2 hover:bg-black transition-all uppercase tracking-wide"
                  >
                    <HiCloudUpload /> Descargar PDF
                  </button>
                )}
              </div>
              <button
                disabled={isProcessing || !idCongreso}
                onClick={handleConfirmSend}
                className="px-8 py-2.5 bg-[#005a6a] text-white rounded-xl font-black text-xs flex items-center justify-center gap-2 hover:bg-[#004a5a] hover:scale-[1.02] active:scale-95 transition-all shadow-lg shadow-[#005a6a]/20 disabled:opacity-50 disabled:cursor-not-allowed"
                title={!idCongreso ? "Seleccione un congreso en el filtro" : ""}
              >
                {isProcessing ? <span className="loading loading-spinner loading-sm"></span> : <HiMail className="text-base" />}
                Confirmar y Enviar
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
