import { useState, useEffect } from "react";
import { HiCloudUpload, HiDocumentText, HiTrash, HiCheckCircle, HiX, HiSparkles, HiMail } from "react-icons/hi";
import CertificateTemplate from "./CertificateTemplate";
import { uploadConstanciaApi } from "../../../api/adminApi";

export default function ConstanciaUpload({ selectedUser, signatures = {}, isSignatureLocked = false, onUploadSuccess }) {
  const [dragActive, setDragActive] = useState(false);
  const [file, setFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [idCongreso] = useState(1); // TODO

  const accessToken = localStorage.getItem('congress_access');

  useEffect(() => {
    if (file && !isAutoGenerated) {
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [file, isAutoGenerated]);

  const handleGenerateAuto = () => {
    if (!isSignatureLocked) {
      alert("⚠️ Debe confirmar las firmas institucionales primero.");
      return;
    }
    setIsProcessing(true);
    setTimeout(() => {
      setFile({ name: `CONSTANCIA_${selectedUser.nombre.toUpperCase()}.pdf` });
      setIsAutoGenerated(true);
      setIsProcessing(false);
      setShowConfirmModal(true);
    }, 1000);
  };

  const handleConfirmSend = async () => {
    setIsProcessing(true);
    try {
      // Si es autogenerado, primero habría que convertir el HTML/Canvas a PDF file.
      // Por ahora, simulamos que enviamos el archivo 'file' que tenemos.
      // En una implementación real, aquí se usaría una librería como html2pdf o jspdf
      // para generar el Blob del archivo antes de subirlo.
      
      let fileToUpload = file;
      if (isAutoGenerated) {
         // Placeholder: En producción esto debe ser un Blob real del PDF generado
         fileToUpload = new File(["constancia"], `constancia_${selectedUser.id}.pdf`, { type: "application/pdf" });
      }

      await uploadConstanciaApi(accessToken, selectedUser.id, idCongreso, fileToUpload, selectedUser.rol);
      
      setIsProcessing(false);
      setShowConfirmModal(false);
      setFile(null);
      setIsAutoGenerated(false);
      if (onUploadSuccess) onUploadSuccess();
    } catch (error) {
      alert("Error al subir constancia");
      setIsProcessing(false);
    }
  };

  const handleDownloadPDF = () => {
    const printContent = document.getElementById('certificate-to-print');
    const uniqueName = `constancia_${selectedUser.nombre.replace(/\s/g, '_')}`;
    
    const printWindow = window.open('', '', 'width=1200,height=800');
    printWindow.document.write(`
      <html>
        <head>
          <title>${uniqueName}</title>
          <script src="https://cdn.tailwindcss.com"></script>
          <style>
            @page { size: landscape; margin: 0; }
            body { margin: 0; -webkit-print-color-adjust: exact; font-family: sans-serif; }
            .print-container { width: 297mm; height: 210mm; }
          </style>
        </head>
        <body>
          <div class="print-container">
            ${printContent.innerHTML}
          </div>
          <script>
            window.onload = () => {
              setTimeout(() => {
                window.print();
                window.close();
              }, 1000);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="bg-[#005a6a] text-white p-8 rounded-3xl shadow-xl h-full flex flex-col gap-6 animate-in slide-in-from-left duration-500">
      <div className="flex justify-between items-start">
        <div>
          <h3 className="text-xl font-bold mb-1">Gestionar Constancia</h3>
          <p className="text-blue-100 text-sm italic">
            Participante: <span className="font-bold underline">{selectedUser?.nombre}</span>
          </p>
        </div>
        <div className="bg-white/10 p-2 rounded-xl border border-white/20">
          <HiSparkles className="text-xl text-yellow-300 animate-pulse" />
        </div>
      </div>

      <div className="grid grid-cols-1 gap-3">
        <button 
          onClick={handleGenerateAuto}
          disabled={isProcessing || !isSignatureLocked}
          className={`w-full py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-lg disabled:opacity-50
            ${isSignatureLocked ? 'bg-yellow-400 text-[#005a6a] hover:bg-yellow-300' : 'bg-gray-400 text-gray-200 cursor-not-allowed shadow-none'}`}
          title={!isSignatureLocked ? "Se requieren firmas confirmadas" : ""}
        >
          {isProcessing ? <span className="loading loading-spinner loading-sm"></span> : <HiSparkles className="text-xl" />}
          Generar desde Plantilla
        </button>
        
        <p className="text-center text-[10px] text-blue-200 uppercase font-bold tracking-widest">— o subir archivo manual —</p>
      </div>

      <div 
        className={`relative border-2 border-dashed rounded-2xl p-6 transition-all flex flex-col items-center justify-center gap-4 text-center min-h-[200px]
          ${dragActive ? "bg-white/10 border-white scale-105" : "border-white/30 hover:border-white/60"}`}
        onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
        onDragLeave={() => setDragActive(false)}
        onDrop={(e) => { e.preventDefault(); setDragActive(false); setIsAutoGenerated(false); setFile(e.dataTransfer.files[0]); }}
      >
        {!file ? (
          <>
            <HiCloudUpload className="text-4xl text-white opacity-50" />
            <label className="px-4 py-2 bg-white/10 rounded-lg text-sm font-bold cursor-pointer hover:bg-white/20 transition-colors">
              Explorar Archivo
              <input type="file" className="hidden" onChange={(e) => { setIsAutoGenerated(false); setFile(e.target.files[0]); }} />
            </label>
          </>
        ) : (
          <div className="w-full animate-in zoom-in duration-300">
            <div className="bg-white/10 p-3 rounded-xl flex items-center gap-3 text-left border border-white/20">
              <HiDocumentText className="text-3xl text-blue-200" />
              <div className="flex-1 overflow-hidden">
                <p className="font-bold text-xs truncate">{file.name}</p>
                <p className="text-[10px] text-blue-200 uppercase font-black">{isAutoGenerated ? "PLANTILLA ACTIVA" : "PDF LISTO"}</p>
              </div>
              <button onClick={() => { setFile(null); setIsAutoGenerated(false); }} className="p-1.5 hover:bg-red-500 rounded-lg transition-colors">
                <HiTrash className="text-lg" />
              </button>
            </div>
            
            <button 
              onClick={() => setShowConfirmModal(true)}
              className="w-full mt-4 py-3 bg-white text-[#005a6a] rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-blue-50 transition-all shadow-lg"
            >
              <HiMail className="text-xl" /> Confirmar y Enviar
            </button>
          </div>
        )}
      </div>

      <div className="mt-auto pt-4 border-t border-white/10 flex justify-between text-[10px] font-bold opacity-60">
        <span>ROL: {selectedUser?.rol.toUpperCase()}</span>
        <span>ID: #{selectedUser?.id.toString().substring(0,6)}</span>
      </div>

      {/* Modal de confirmación con Plantilla Viva */}
      {showConfirmModal && (
        <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4 lg:p-10">
          <div className="absolute inset-0 bg-black/90 backdrop-blur-md" onClick={() => !isProcessing && setShowConfirmModal(false)}></div>
          <div className="relative bg-white text-gray-800 w-full max-w-6xl rounded-3xl shadow-2xl overflow-hidden flex flex-col h-full max-h-[95vh]">
            <div className="p-4 border-b flex justify-between items-center bg-gray-50 shrink-0">
              <div className="flex items-center gap-3 text-[#005a6a]">
                 <HiSparkles className="text-2xl" />
                 <h3 className="font-black uppercase tracking-tighter text-sm">Previsualización de Constancia Automática</h3>
              </div>
              <button onClick={() => setShowConfirmModal(false)} className="p-2 hover:bg-gray-200 rounded-full transition-colors"><HiX className="text-xl text-gray-400" /></button>
            </div>
            
            <div className="p-6 flex-1 bg-gray-200 overflow-auto flex items-start justify-center">
               <div id="certificate-to-print" className="w-full max-w-5xl shadow-2xl origin-top">
                  {isAutoGenerated ? (
                    <CertificateTemplate user={selectedUser} signatures={signatures} />
                  ) : (
                    <iframe src={previewUrl} className="w-full aspect-[1.414/1] rounded-lg border-none shadow-2xl" title="Preview manual" />
                  )}
               </div>
            </div>

            <div className="p-6 bg-white border-t flex flex-col sm:flex-row gap-4 shrink-0">
              <div className="flex-1 flex gap-3">
                <button disabled={isProcessing} onClick={() => setShowConfirmModal(false)} className="px-6 py-3 border-2 border-gray-100 rounded-2xl font-black text-gray-400 hover:bg-gray-50 transition-all uppercase text-xs tracking-widest">Cerrar</button>
                <button 
                  onClick={handleDownloadPDF}
                  className="px-6 py-3 bg-gray-800 text-white rounded-2xl font-black flex items-center justify-center gap-2 hover:bg-black transition-all uppercase text-xs tracking-widest shadow-lg"
                >
                  <HiCloudUpload className="text-lg" /> Descargar PDF
                </button>
              </div>
              <button disabled={isProcessing} onClick={handleConfirmSend} className="px-10 py-3 bg-[#005a6a] text-white rounded-2xl font-black flex items-center justify-center gap-3 shadow-xl hover:scale-105 active:scale-95 transition-all uppercase text-xs tracking-widest">
                {isProcessing ? <span className="loading loading-spinner loading-sm"></span> : <HiMail className="text-xl" />}
                Confirmar y Enviar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
