# Generated by Django 6.0.4 on 2026-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id_asistente_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'asistente_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id_ponencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_participacion', models.CharField(max_length=50)),
                ('id_resumen', models.IntegerField(blank=True, null=True)),
                ('id_extenso', models.IntegerField(blank=True, null=True)),
                ('id_multimedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ponencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PonenteHasPonencia',
            fields=[
                ('id_ponente_has_ponencia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ponente_has_ponencia',
                'managed': False,
            },
        ),
    ]
