# Generated by Django 6.0.4 on 2026-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id_asistente_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'asistente_evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictamenResumen',
            fields=[
                ('id_dictamen', models.AutoField(primary_key=True, serialize=False)),
                ('retroalimentacion_general', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(max_length=50)),
                ('fecha_de_revision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dictamen_resumen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('retroalimentacion_general', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(max_length=100)),
                ('fecha_de_revision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id_evaluacion_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField(null=True)),
                ('comentario_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_criterio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPregunta',
            fields=[
                ('id_evaluacion_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('id_pregunta_id', models.IntegerField(db_column='id_pregunta')),
                ('cumplio', models.BooleanField(null=True)),
                ('comentario_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extenso',
            fields=[
                ('id_extenso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ruta_relativa', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('version_numero', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'extenso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id_ponencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_participacion', models.CharField(max_length=50)),
                ('id_resumen', models.IntegerField(blank=True, null=True)),
                ('id_extenso', models.IntegerField(blank=True, null=True)),
                ('id_multimedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ponencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PonenciaMagistral',
            fields=[
                ('id_ponencia_magistral', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_participacion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_multimedia', models.IntegerField(blank=True, null=True)),
                ('enlace_multimedia', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'ponencia_magistral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PonenciaMagistralHasPonentemagistral',
            fields=[
                ('id_ponencia_magistral_has_ponente_magistral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=100)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ponencia_magistral_has_ponente_magistral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PonenteHasPonencia',
            fields=[
                ('id_ponente_has_ponencia', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ponente_has_ponencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resumen',
                'managed': False,
            },
        ),
    ]
