# Generated by Django 6.0.4 on 2026-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponencias', '0003_extenso_evaluadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictamenResumen',
            fields=[
                ('id_dictamen', models.AutoField(primary_key=True, serialize=False)),
                ('retroalimentacion_general', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(max_length=50)),
                ('fecha_de_revision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dictamen_resumen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('retroalimentacion_general', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(max_length=100)),
                ('fecha_de_revision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('id_evaluacion_criterio', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField(null=True)),
                ('comentario_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_criterio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPregunta',
            fields=[
                ('id_evaluacion_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('id_pregunta_id', models.IntegerField(db_column='id_pregunta')),
                ('cumplio', models.BooleanField(null=True)),
                ('comentario_especifico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extenso',
            fields=[
                ('id_extenso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ruta_relativa', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('version_numero', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'extenso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resumen',
                'managed': False,
            },
        ),
    ]
