# Generated by Django 6.0.5 on 2026-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponencias', '0004_dictamenresumen_evaluacion_evaluacioncriterio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PonenciaMagistral',
            fields=[
                ('id_ponencia_magistral', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_participacion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('id_multimedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ponencia_magistral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PonenciaMagistralHasPonentemagistral',
            fields=[
                ('id_ponencia_magistral_has_ponente_magistral', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_persona', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ponencia_magistral_has_ponente_magistral',
                'managed': False,
            },
        ),
    ]
