# Generated by Django 6.0.3 on 2026-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asistente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictaminador',
            fields=[
                ('id_dictaminador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dictaminador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id_evaluador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id_ponente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ponente',
                'managed': False,
            },
        ),
    ]
