# Generated by Django 6.0.4 on 2026-05-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congresos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('num_telefono', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id_constancia', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_constancia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_constancia', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(default='generada', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'constancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictaminador',
            fields=[
                ('id_dictaminador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dictaminador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id_evaluador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evaluador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_pdf_xml', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_constancia_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id_historial_acciones', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historial_acciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id_ponente', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ponente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id_asistente', models.AutoField(primary_key=True, serialize=False)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('es_estudiante_validado', models.BooleanField(default=False)),
                ('email_institucional', models.EmailField(blank=True, max_length=255, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('fecha_envio_codigo', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictaminadorCongreso',
            fields=[
                ('id_dictaminador_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_congreso', models.ForeignKey(db_column='id_congreso', on_delete=django.db.models.deletion.CASCADE, related_name='dictaminadores', to='congresos.congreso')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='dictaminador_congresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dictaminador_congreso',
                'unique_together': {('id_persona', 'id_congreso')},
            },
        ),
        migrations.CreateModel(
            name='EvaluadorCongreso',
            fields=[
                ('id_evaluador_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_congreso', models.ForeignKey(db_column='id_congreso', on_delete=django.db.models.deletion.CASCADE, related_name='evaluadores', to='congresos.congreso')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='evaluador_congresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluador_congreso',
                'unique_together': {('id_persona', 'id_congreso')},
            },
        ),
    ]
