# Generated by Django 6.0.4 on 2026-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id_constancia', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_constancia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_constancia', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(default='generada', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'constancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta_pdf_xml', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id_historial_acciones', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historial_acciones',
                'managed': False,
            },
        ),
    ]
