# Generated by Django 6.0.4 on 2026-05-02 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congresos', '0001_initial'),
        ('users', '0002_constancia_factura_historialacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictaminadorCongreso',
            fields=[
                ('id_dictaminador_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_congreso', models.ForeignKey(db_column='id_congreso', on_delete=django.db.models.deletion.CASCADE, related_name='dictaminadores', to='congresos.congreso')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='dictaminador_congresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dictaminador_congreso',
                'unique_together': {('id_persona', 'id_congreso')},
            },
        ),
        migrations.CreateModel(
            name='EvaluadorCongreso',
            fields=[
                ('id_evaluador_congreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_congreso', models.ForeignKey(db_column='id_congreso', on_delete=django.db.models.deletion.CASCADE, related_name='evaluadores', to='congresos.congreso')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='evaluador_congresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluador_congreso',
                'unique_together': {('id_persona', 'id_congreso')},
            },
        ),
    ]
