# Generated by Django 5.2.12 on 2026-05-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dictaminadorcongreso_evaluadorcongreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistente',
            options={'managed': True},
        ),
    ]
