# Generated by Django 5.2.12 on 2026-05-09 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_asistente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='email_institucional',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='es_estudiante_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistente',
            name='fecha_envio_codigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistente',
            name='id_persona',
            field=models.OneToOneField(db_column='id_persona', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
